accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import SignUpView


urlpatterns = [
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("signup/", SignUpView.as_view(), name="signup"),
]

projects/urls.py
from projects.views import P_ListView, P_DetailView, P_CreateView
from django.urls import path


urlpatterns = [
    path("", P_ListView.as_view(), name="list_projects"),
    path("<int:pk>/", P_DetailView.as_view(), name="show_project"),
    path("create/", P_CreateView.as_view(), name="create_project"),
]

tasks/urls.py
from django.urls import path
from tasks.views import Task_CreateView, Task_ListView, Task_UpdateView

urlpatterns = [
    path("create/", Task_CreateView.as_view(), name="create_task"),
    path("mine/", Task_ListView.as_view(), name="show_my_tasks"),
    path(
        "<int:pk>/complete/", Task_UpdateView.as_view(), name="complete_task"
    ),
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path("", RedirectView.as_view(pattern_name="list_projects"), name="home"),
    path("accounts/", include("accounts.urls")),
    path("tasks/", include("tasks.urls")),
]

accounts/models.py
# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL
# Create your models here.


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    members = models.ManyToManyField(USER_MODEL, related_name="projects")

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings
from projects.models import Project

# Create your models here.
USER_MODEL = settings.AUTH_USER_MODEL


class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField()
    due_date = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        USER_MODEL, null=True, related_name="tasks", on_delete=models.SET_NULL
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("home")
    template_name = "registration/signup.html"

projects/views.py
from .models import Project
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

# Create your views here.


class P_ListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "p_list.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class P_DetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "p_detail.html"

    def get_queryset(self):
        return Project.objects.filter(members=self.request.user)


class P_CreateView(LoginRequiredMixin, CreateView):
    model = Project
    template_name = "create.html"
    fields = ["name", "description", "members"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.pk])

tasks/views.py
from django.views.generic import CreateView, ListView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Task

# Create your views here.


class Task_CreateView(LoginRequiredMixin, CreateView):
    model = Task
    template_name = "createTask.html"
    fields = ["name", "start_date", "due_date", "project", "assignee"]

    def get_success_url(self):
        return reverse_lazy("show_project", args=[self.object.project.pk])

    # def form_valid(self, form):
    #     task = form.save(commit=False)
    #     task.assignee = self.request.user
    #     task.save()
    #     return redirect("show_project", pk=task.project.id)


class Task_ListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "list_view.html"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)


class Task_UpdateView(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = "list_view.html"
    fields = ["is_completed"]
    success_url = "/tasks/mine/"

    def get_queryset(self):
        return Task.objects.filter(assignee=self.request.user)

projects/templates/create.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a New Project Page</title>
    </head>
    <body style="background-color:grey;">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new project</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="text" name="name">
                    <textarea name="description"></textarea>
                    <select name="members"></select>
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

projects/templates/p_detail.html
{% load markdownify %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body style="background-color:grey;">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>{{ project.name }}</h1>
                {{ project.description|markdownify }}
                <h2>Tasks</h2>
                <a href="{% url "create_task" %}">Create a new task</a>
                {% if project.tasks.all|length == 0 %}
                    <p>This project has no tasks</p>
                {% else %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Assignee</th>
                            <th>Start date</th>
                            <th>Due date</th>
                            <th>Is completed</th>
                        </tr>
                {% endif %}
                {% for x in project.tasks.all %}
                    <tr>
                        <td>{{ x.name }}</td>
                        <td>{{ x.assignee }}</td>
                        <td>{{ x.start_date }}</td>
                        <td>{{ x.due_date }}</td>
                        {% if x.is_completed == True %}
                            <td>yes</td>
                        {% else %}
                            <td>no</td>
                        {% endif %}
                    </tr>
                    </table>
                {% endfor %}
            </div>
        </main>
    </body>
</html>

projects/templates/p_list.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>
    <body style="background-color:grey;">
        <header>
            <nav>
            </header>
            <ul>
                {% if user.is_authenticated %}
                    <li>
                        <a href="{% url "show_my_tasks" %}">My tasks</a>
                    </li>
                    <li>
                        <a href="{% url "list_projects" %}">My projects</a>
                    </li>
                    <li>
                        <a href="{% url "logout" %}">Logout</a>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url "login" %}">Login</a>
                    </li>
                    <li>
                        <a href="{% url "signup" %}">Signup</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <main>
            <div>
                <h1>My Projects</h1>
                <a href="{% url "create_project" %}">Create a new project</a>
                {% if project_list|length == 0 %}
                    <p>You are not assigned to any projects</p>
                {% else %}
                    <table>
                        <tr>
                            <th>Name</th>
                            <th>Number of Tasks</th>
                        </tr>
                        {% for x in project_list %}
                            <tr>
                                {% comment %} <td>{{ x.name }}</td> {% endcomment %}
                                <td><a href="{% url "show_project" x.pk %}">{{ x.name }}</a></td>
                                <td>{{ x.tasks.all|length }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                {% endif %}
            </div>
        </main>
    </body>
</html>

tasks/templates/createTask.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Create a new task</title>
    </head>
    <body style="background-color:grey;">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <main>
            <div>
                <h1>Create a new task</h1>
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    {% comment %} <input type="text" name="name">
                <textarea name="description"></textarea>
                <select name="members"></select> {% endcomment %}
                    <button>Create</button>
                </form>
            </div>
        </main>
    </body>
</html>

tasks/templates/list_view.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Tasks</title>
    </head>
    <body style="background-color: #FFFFE0;">
        <header>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                        <li>
                            <a href="{% url "show_my_tasks" %}">My tasks</a>
                        </li>
                        <li>
                            <a href="{% url "list_projects" %}">My projects</a>
                        </li>
                        <li>
                            <a href="{% url "logout" %}">Logout</a>
                        </li>
                    {% else %}
                        <li>
                            <a href="{% url "login" %}">Login</a>
                        </li>
                        <li>
                            <a href="{% url "signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </header>
                <main>
                    <div>
                        <h1>My Tasks</h1>
                        {% if task_list|length == 0 %}
                            <p>You have no tasks</p>
                        {% else %}
                            <table>
                                <tr>
                                    <th>Name</th>
                                    <th>Start date</th>
                                    <th>End date</th>
                                    <th>Is completed</th>
                                </tr>
                                {% for x in task_list %}
                                    <tr>
                                        <td>{{ x.name }}</td>
                                        <td>{{ x.start_date }}</td>
                                        <td>{{ x.due_date }}</td>
                                        {% if x.is_completed == True %}
                                            <td>Done</td>
                                        {% else %}
                                            <td>
                                                <form method="POST" action="{% url 'complete_task' x.id %}">
                                                    {% csrf_token %}
                                                    <input type="hidden" name="is_completed" value="True">
                                                    <button>Complete</button>
                                                </form>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </table>
                        {% endif %}
                    </div>
                </main>
    </body>
</html>